---
- hosts: all
  become: True
  tasks:
    - include: tasks/deps.yml

    # get everything up to date and runit installed
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: install packagecloud repo
      yum_repository:
        name: imeyer_runit
        description: imeyer_runit
        baseurl: https://packagecloud.io/imeyer/runit/el/6/$basearch
        repo_gpgcheck: yes
        gpgcheck: no
        gpgkey: https://packagecloud.io/imeyer/runit/gpgkey
        sslverify: yes
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt
        metadata_expire: 300
    - name: install runit package
      yum:
        name: runit
        state: latest

    # Get the app going!
    - name: create /opt
      file:
        path: /opt
        state: directory
    - name: unpack app in app homedir
      unarchive:
        src: application.zip
        dest: /opt
    - name: create application sv dir
      file:
        path: /etc/service/application
        state: directory
    - name: set up runit start script
      copy:
        src: /opt/application/run
        dest: /etc/service/application
        mode: 0755
        remote_src: yes
    - name: make sure that app is running
      runit:
        name: application
        state: started

    # get nginx installed, configured, and running
    - name: install latest nginx
      yum:
        name: nginx
        state: latest
    - name: install nginx config
      copy:
        src: config/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: 
      - reload nginx
    - name: create key dir
      file:
        path: /etc/ssl/private
        state: directory
        owner: root
        group: root
        mode: 0700
        recurse: yes
    - name: install nginx cert
      copy:
        src: files/self-signed.crt
        dest: /etc/ssl/certs/self-signed.crt
        owner: root
        group: root
        mode: 0640
      notify: 
      - reload nginx
    - name: install nginx key
      copy:
        src: files/self-signed.key
        dest: /etc/ssl/private/self-signed.key
        owner: root
        group: root
        mode: 0600
      notify: 
      - reload nginx
    - name: create dhparam file
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
      args:
        creates: /etc/ssl/certs/dhparam.pem
    - name: ensure nginx is running and restarts when host is rebooted
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded

